@startuml
box "Future"
    participant "f : Future" as f
end box
box "Servant"
    participant "d: Diffusion" as d
    participant "g: Generator" as g
end box
box "Method Invocation"
    participant "mi : GetValueCallable" as mi
end box
box "Scheduler"
    participant "s : Scheduler" as s
end box
activate g
activate s
s -> mi: call()
activate mi
mi -> d: getValue(c)
deactivate mi
activate d
d -> g: getValue()
deactivate d
g --> d: v
activate d
d --> mi: v
deactivate d
activate mi
mi --> s: v
deactivate mi
s -> f: setDone()
activate f
deactivate f
@enduml